models and tests ok
fabiuhp/sunty pull request #1
Opened 2021-06-11 17:21 UTC by fabiuhp

2021-06-11 17:59 UTC, fabiuhp commented
Ainda existem pontos a serem feitos.

2021-06-14 16:32 UTC, alexandreaquiles commented on src/br/com/sunty/models/validations/Validation.java
> +    }
Aqui o nome do método não deveria ser `nonEmptyFieldValidation`?

2021-06-14 16:46 UTC, alexandreaquiles commented on src/br/com/sunty/models/Category/Category.java
> +    private String hexColorHtml;
O nome dá a entender que é um HTML, mas na verdade é uma cor do HTML. Acho que `hexHtmlColor` seria mais claro.

2021-06-14 16:47 UTC, alexandreaquiles commented on src/br/com/sunty/models/validations/Validation.java
> +            throw new IllegalArgumentException(err);
Perfeita a exceção que você escolheu! :1st_place_medal:

2021-06-14 16:47 UTC, alexandreaquiles commented on src/br/com/sunty/models/validations/Validation.java
> +public class Validation {
Essa classe ficou muito boa. Parabéns! :1st_place_medal:

2021-06-14 16:51 UTC, alexandreaquiles commented on src/br/com/sunty/models/validations/Validation.java
> +        if (!urlCode.matches("[-?a-z]+")) {
Aqui está deixando cadastrar URL com `?`, que não está de acordo com o card.

2021-06-14 16:54 UTC, alexandreaquiles commented on src/br/com/sunty/models/Category/Category.java
> +package br.com.sunty.models.Category;
A convenção de pacotes no Java é sempre usar tudo minúsculo, sem nem camelCase.
```suggestion
package br.com.sunty.models.category;
```

2021-06-14 16:55 UTC, alexandreaquiles commented on src/br/com/sunty/models/Category/SubCategory/SubCategory.java
> +package br.com.sunty.models.Category.SubCategory;
Mesmo problema de convenções no nome do pacote. Deveria ser tudo minúsculo.

Achei legal você colocar `Category` e `SubCategory` juntas, mas poderia ser no mesmo pacote. Não acho que há a necessidade de um pacote específico pra subcategorias.

2021-06-14 16:55 UTC, alexandreaquiles commented on src/br/com/sunty/models/activity/Explanation.java
> +        super.setSection(section);
Ao invés de usar setters, seria melhor usar construtores.

2021-06-14 16:57 UTC, alexandreaquiles commented on src/br/com/sunty/models/activity/utils/Activity.java
> +
Poderia definir um construtor com as validações aqui na classe mãe.

2021-06-14 16:57 UTC, alexandreaquiles commented on src/br/com/sunty/models/activity/utils/QuestionType.java
> +    TRUEORFALSE, MULTIPLEANSWER, ONEANSWER;
É interessante colocar um `_` entre as palavras para melhorar a legibilidade dos valores da enum.

2021-06-14 16:58 UTC, alexandreaquiles commented on src/br/com/sunty/models/course/Course.java
> +    private Integer timeForFinish;
Acho que _to_ ao invés de _for_.

```suggestion
    private Integer timeToFinish;
```

2021-06-14 16:59 UTC, alexandreaquiles commented on src/br/com/sunty/models/course/Course.java
> +    private Instructor instructor;
Achei interessante instrutor já ser uma classe.

2021-06-14 17:00 UTC, alexandreaquiles commented on src/br/com/sunty/models/validations/Validation.java
> +    public static void intervalValidation(Integer minimumTime, Integer maximumTime, Integer timeForFinish, String err) {
O que acontece se eu passar `null` nos parâmetros?

2021-06-14 17:02 UTC, alexandreaquiles commented on src/br/com/sunty/models/Category/Category.java
> +    public Category(Long id, String name, String urlCode) {
Id não é um campo necessário. Pode ser que eu não tenha um id. Talvez não precise estar no construtor nesse momento. Ou ter um construtor sem id.

2021-06-14 17:04 UTC, alexandreaquiles commented on src/br/com/sunty/models/course/Course.java
> +
Seria interessante reforçar o valor padrão da enum da visibilidade do curso.

2021-06-14 17:05 UTC, alexandreaquiles commented on src/br/com/sunty/models/course/Course.java
> +    private CourseVisibility courseVisibility;
Já estamos na classe `Course`, não há a necessidade do atributo ter `course` como prefixo.

```suggestion
    private CourseVisibility visibility;
```

2021-06-14 17:07 UTC, alexandreaquiles commented on src/br/com/sunty/models/section/Section.java
> +    private Boolean isActive = true;
O valor padrão aqui está como é uma prova e está ativa ao mesmo tempo. Isso não está de acordo com a especificação.

Além disso, _test_ é um nome complicado porque indica um teste automatizado no contexto técnico. Será que teríamos um outro nome?

2021-06-14 17:11 UTC, alexandreaquiles commented on src/br/com/sunty/models/Category/Category.java
> +        urlValidation(urlCode, "Url só deve conter letras minusculas e traços.");
E se a `urlCode` estiver nula?

2021-06-14 17:12 UTC, alexandreaquiles commented on src/br/com/sunty/models/activity/Video.java
> +        super.setSection(section);
Seria legal ter um construtor na mãe.

2021-06-14 17:12 UTC, alexandreaquiles commented on src/br/com/sunty/models/activity/Video.java
> +    private Integer time;
Sempre é interessante colocar a unidade de medida. É em minutos, em horas ou em segundos?

2021-06-14 17:13 UTC, alexandreaquiles commented on src/br/com/sunty/models/activity/Question.java
> +        super.setSection(section);
Seria legal ter um construtor na mãe.

2021-06-14 17:14 UTC, alexandreaquiles commented on src/br/com/sunty/models/activity/Question.java
> +    public Question(Long id, String name, String urlCode, Section section, String description, QuestionType questionType) {
Seria interessante checar se a descrição está preenchida, já que é obrigatória.

2021-06-14 17:16 UTC, alexandreaquiles commented on src/br/com/sunty/models/alternative/Alternative.java
> +    private String justificative;
Acho que seria _justification_. O termo _justificative_ parece ser um adjetivo.

2021-06-14 17:17 UTC, alexandreaquiles reviewed
O nome da PR está bom, mas poderia descrever que é uma modelagem da parte de aulas e categorias.

Seria legal remover os `.class` do respositório e colocar diretório `out` no `.gitignore`.

2021-06-14 17:41 UTC, fabiuhp commented on src/br/com/sunty/models/validations/Validation.java
> +    public static void intervalValidation(Integer minimumTime, Integer maximumTime, Integer timeForFinish, String err) {
Vai lançar NullPointerException, por que o Java não vai conseguir invocar o método java.lang.Integer.intValue().

2021-06-14 17:52 UTC, alexandreaquiles commented on src/br/com/sunty/models/validations/Validation.java
> +    public static void intervalValidation(Integer minimumTime, Integer maximumTime, Integer timeForFinish, String err) {
Boa! Onde resolver isso? Aqui, lá onde esse código é chamado ou nos 2 lugares? E se modificar os tipos na assinatura do método. Ajuda em algo?

2021-06-14 17:54 UTC, fabiuhp commented on src/br/com/sunty/models/Category/Category.java
> +        urlValidation(urlCode, "Url só deve conter letras minusculas e traços.");
Lança NullPointerException porque o matches já obriga um valor ali dentro.

2021-06-14 17:54 UTC, alexandreaquiles commented on src/br/com/sunty/models/validations/Validation.java
> +    public static void intervalValidation(Integer minimumTime, Integer maximumTime, Integer timeForFinish, String err) {
Foi mal @fabiuhp pelo meu momento mestre dos magos. Joga uma pergunta e cai fora... :rofl: 

![image](https://user-images.githubusercontent.com/258331/121936701-4a0dd480-cd20-11eb-9fcb-a57f2b4380eb.png)

2021-06-14 20:46 UTC, alexandreaquiles requested changes

2021-06-14 20:46 UTC, alexandreaquiles commented on src/br/com/sunty/models/activity/Activity.java
> +        this.section = section;
Será que as validações não poderiam estar aqui e não serem feitas em cada uma das classes filhas?

2021-06-16 01:03 UTC, fabiuhp commented on src/br/com/sunty/models/course/Course.java
> +        this.subCategory = subCategory;
Foi requisito dos cards essa.

2021-06-16 13:21 UTC, GesleyElois commented on src/br/com/sunty/models/activity/Activity.java
> +    private Boolean isActive;
Poderia usar um tipo primitivo, assim evitamos um NPE e também não precisaria da validação deste campo

2021-06-16 13:31 UTC, GesleyElois approved these changes

2021-06-16 14:12 UTC, GesleyElois commented on src/br/com/sunty/models/activity/Video.java
> +        this.url = url;
Validar se a URL não está vazia ou nulo, por ser um campo obrigatório

2021-06-16 14:12 UTC, alexandreaquiles commented on src/br/com/sunty/models/course/Course.java
> +        this.subCategory = subCategory;
Opa, @fabiuhp. É que o @andradeoromulo tem uma ideia diferente de modelagem: ao invés de ter classes para representar categoria e subcategoria, ele pensou em ter apenas categoria. Aí, uma subcategoria seria uma categoria com uma categoria "mãe". As categorias "raiz" não teriam uma categoria mãe.

2021-06-16 14:13 UTC, alexandreaquiles commented on src/br/com/sunty/models/category/SubCategory.java
> +
Mencionei a ideia da autoreferência aqui: https://github.com/fabiuhp/sunty/pull/1#discussion_r652730792

2021-06-16 14:43 UTC, GesleyElois approved these changes

2021-06-16 14:58 UTC, alexandreaquiles approved these changes
Aprovado!

2021-06-16 14:58 UTC, merged